require('dotenv').config()
const express = require('express')
const authRoute = require('./src/routes/authRoute')
const app = express()
const errorHandler = require('./src/middleware/error')
const notFoundHandler = require('./src/middleware/not-found')
const postRoute = require('./src/routes/postRoute')
const PORT = process.env.PORT
app.use(express.json())
app.use('/auth', authRoute)
app.use('/post', postRoute)
app.use('*', notFoundHandler)
app.use(errorHandler)

app.listen(PORT, () => console.log(`THIS APP IS RUNNING ON PORT ${PORT}`))