require('dotenv').config()
const express = require('express')
const authRoute = require('./routes/authRoute')
const app = express()
const errorHandler = require('./middleware/error')
const notFoundHandler = require('./middleware/not-found')
const postRoute = require('./routes/postRoute')
app.use(express.json())
app.use('/auth', authRoute)
app.use('/post', postRoute)
app.use('*', notFoundHandler)
app.use(errorHandler)

app.listen('8000', () => console.log('THIS APP IS RUNNING ON PORT 8000'))